### PR TITLE
Add an OAuth2Credentials and getEmails

### PR DESCRIPTION
**Pull request by mw-ding**
This is quite straightforward, just place `access_token` as a query string in the url.

### CODE REVIEW

**Comment by mw-ding** [comment]
@rtfpessoa any chance to take a look?

**Comment by mw-ding** [comment]
@rtfpessoa sure. added a unit test for `Email`.

**Comment by rtfpessoa** [comment]
@mw-ding can you amend the last commit for CircleCI to trigger the analysis. Seems like it was not building forked PRs.

**Comment by mw-ding** [comment]
@rtfpessoa pushed again. can you re-approve? 

Also, it's appreciated if you can help to make a new minor version release after this PR being merged?

**Comment by mw-ding** [comment]
image

Looks like I cannot merge the PR. @rtfpessoa

**Comment by rtfpessoa** [comment]
Had to bring master in after that I will do a release.

**Comment by rtfpessoa** [comment]
Released as version `5.1.0`

**Pull request merged**
