### PR TITLE
Handle possible exception on parseJson and fix null author on json

### PR DESCRIPTION
**Pull request by machadoit**

### CODE REVIEW

**Comment by mrfyda** [comment]
Tests, please.

**Comment by machadoit** [comment]
I didn't had any test, because I didn't change anything, I kinda forget that this PR was not just to add logs in case of failure 👍 

Add the fix on the null author on json, and added a test for it

**Comment by machadoit** [comment]
Status from circleCI seems to be stuck, but the build is successful. @mrfyda is it ok to merge?

**Comment by rtfpessoa** [comment]
No

**Pull request merged**
